#!/bin/bash
# =============================================================
# TiX-One Step 2: Create Concert on-chain for each concert
# Run ONCE after deployment. Creates one shared Concert object
# per concert and outputs Supabase SQL to update concert_object_id.
# =============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IDS_FILE="$SCRIPT_DIR/.deployed-ids.env"
SQL_FILE="$SCRIPT_DIR/supabase-update.sql"

# ---- Load deployed IDs ----
if [ ! -f "$IDS_FILE" ]; then
  echo "❌  $IDS_FILE not found."
  echo "    Run scripts/1-deploy.sh first."
  exit 1
fi
source "$IDS_FILE"

if [ -z "$PACKAGE_ID" ] || [ -z "$ADMIN_CAP_ID" ]; then
  echo "❌  PACKAGE_ID or ADMIN_CAP_ID is missing in $IDS_FILE"
  exit 1
fi

echo ""
echo "🎵  Creating Concert objects on-chain..."
echo "    Package   : $PACKAGE_ID"
echo "    Admin Cap : $ADMIN_CAP_ID"
echo ""

# ---- Concert data: "id|artist|event_name|available_tickets|price_mist" ----
# price_mist = OCT price × 1_000_000_000  (matches the price TEXT column, e.g. "0.05 OCT" → 50000000)
# available_tickets = real on-chain max supply (used for "availableTickets" column + Concert.max_supply)
declare -a CONCERTS=(
  "1|Martin Garrix|Neon Dreams Tour|2|50000000"
  "2|Taylor Swift|Celestial Sound Experience|2|80000000"
  "3|Calvin Harris|Blockchain Beats Festival|2|120000000"
  "4|Ed Sheeran|Unplugged & Unchained|2|40000000"
  "5|Drake|Decentralized Sound Tour|2|70000000"
  "6|Billie Eilish|Galaxy Tour 2026|2|60000000"
  "7|Bruno Mars|Smooth Grooves Night|2|30000000"
  "8|The Weeknd|Rock Revolution Tour|2|90000000"
  "9|Coldplay|Blockchain Classics|2|100000000"
  "10|Post Malone|Country Roads Festival|2|45000000"
  "11|Linkin Park|Metal Mayhem World Tour|2|70000000"
  "12|Rihanna|Island Rhythms Festival|2|35000000"
  "13|Shakira|Salsa Heat Night|2|55000000"
  "14|Dua Lipa|Techno Underground|2|65000000"
  "15|Adele|Blues Heritage Tour|2|50000000"
)

# ---- Begin SQL file ----
cat > "$SQL_FILE" <<EOF
-- ============================================================
-- Supabase: paste this into the SQL Editor to link on-chain IDs
-- Generated by scripts/2-seed-concerts.sh
-- ============================================================

EOF

FAILED=0

for entry in "${CONCERTS[@]}"; do
  IFS='|' read -r CONCERT_ID ARTIST EVENT_NAME AVAILABLE_TICKETS PRICE_MIST <<< "$entry"

  echo -n "  [$CONCERT_ID] $EVENT_NAME ($ARTIST) ... "

  # Call create_concert on-chain
  RESULT=$(one client call \
    --package "$PACKAGE_ID" \
    --module ticket \
    --function create_concert \
    --args "$ADMIN_CAP_ID" "$ARTIST" "$EVENT_NAME" "$AVAILABLE_TICKETS" \
    --gas-budget 10000000 \
    --json 2>/dev/null)

  # Extract the new Concert shared object ID
  OBJECT_ID=$(echo "$RESULT" | \
    python3 -c "
import sys, json
data = json.load(sys.stdin)
changes = data.get('objectChanges', [])
for c in changes:
    t = c.get('objectType', '')
    if '::ticket::Concert' in t and c.get('type') == 'created':
        print(c['objectId'])
        break
" 2>/dev/null)

  if [ -z "$OBJECT_ID" ]; then
    echo "❌  FAILED"
    FAILED=$((FAILED + 1))
    # Append a placeholder so the SQL file is still useful
    echo "-- ❌ FAILED: $EVENT_NAME (id=$CONCERT_ID)" >> "$SQL_FILE"
    continue
  fi

  echo "✅  $OBJECT_ID"

  # Append UPDATE statement to SQL file
  # Uses your exact column names: "availableTickets" (quoted, camelCase), price (TEXT e.g. "0.05 OCT")
  # Derive OCT price string from PRICE_MIST (divide by 1_000_000_000)
  PRICE_OCT=$(python3 -c "
mist = $PRICE_MIST
oct_val = mist / 1_000_000_000
# Format: remove trailing zeros but keep at least 2 decimal places
s = f'{oct_val:.9f}'.rstrip('0')
if '.' in s:
    parts = s.split('.')
    dec = parts[1] if len(parts[1]) >= 2 else parts[1].ljust(2, '0')
    s = parts[0] + '.' + dec
print(s + ' OCT')
")
  cat >> "\$SQL_FILE" <<EOF
UPDATE concerts
SET concert_object_id   = '\$OBJECT_ID',
    artist              = '\$ARTIST',
    \"availableTickets\"  = \$AVAILABLE_TICKETS,
    price               = '\$PRICE_OCT'
WHERE id = '\$CONCERT_ID';   -- \$EVENT_NAME

EOF
done

echo ""
if [ "$FAILED" -gt 0 ]; then
  echo "⚠️   $FAILED concert(s) failed — check output above."
else
  echo "🎉  All concerts created successfully!"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NEXT STEP:"
echo "  1. Open Supabase → SQL Editor"
echo "  2. Paste the contents of:"
echo "     $SQL_FILE"
echo "  3. Run the query"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ---- Also update src/onechain/config.ts ----
CONFIG_FILE="$SCRIPT_DIR/../src/onechain/config.ts"

echo "  Updating src/onechain/config.ts with new IDs..."

python3 - <<PYEOF
import re

with open("$CONFIG_FILE", "r") as f:
    content = f.read()

replacements = {
    r'(export const PACKAGE_ID\s*=\s*")[^"]+(")',
    r'(export const LISTING_REGISTRY_ID\s*=\s*")[^"]+(")',
}

content = re.sub(
    r'(export const PACKAGE_ID\s*=\s*")[^"]+(")',
    r'\g<1>$PACKAGE_ID\g<2>',
    content
)
content = re.sub(
    r'(export const LISTING_REGISTRY_ID\s*=\s*")[^"]+(")',
    r'\g<1>$LISTING_REGISTRY_ID\g<2>',
    content
)
content = re.sub(
    r'(export const ADMIN_CAP_ID\s*=\s*")[^"]+(")',
    r'\g<1>$ADMIN_CAP_ID\g<2>',
    content
)

with open("$CONFIG_FILE", "w") as f:
    f.write(content)

print("  ✅  config.ts updated.")
PYEOF
