#!/bin/bash
# =============================================================
# TiX-One Step 4: Create Waitlist objects on-chain per concert
# Run ONCE after 2-seed-concerts.sh.
# Creates one shared Waitlist per concert and outputs full
# Supabase SQL to update both concert_object_id AND waitlist_object_id.
# =============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IDS_FILE="$SCRIPT_DIR/.deployed-ids.env"
SQL_FILE="$SCRIPT_DIR/supabase-update.sql"

# ---- Load deployed IDs ----
if [ ! -f "$IDS_FILE" ]; then
  echo "❌  $IDS_FILE not found."
  echo "    Run scripts/1-deploy.sh first."
  exit 1
fi
source "$IDS_FILE"

if [ -z "$PACKAGE_ID" ] || [ -z "$ADMIN_CAP_ID" ]; then
  echo "❌  PACKAGE_ID or ADMIN_CAP_ID is missing in $IDS_FILE"
  exit 1
fi

echo ""
echo "⏳  Creating Waitlist objects on-chain..."
echo "    Package   : $PACKAGE_ID"
echo "    Admin Cap : $ADMIN_CAP_ID"
echo ""

# ---- Concert data: "supabase_id|concert_object_id|face_value_mist|artist|event_name" ----
# These concert_object_ids were captured by 2-seed-concerts.sh
declare -a DATA=(
  "1|0xa44532d726037600dd0794a51a840f6a425da3461f20ded52cc26f687a8c1fb3|50000000|Martin Garrix|Neon Dreams Tour"
  "2|0x3bb456f38018f41e215148220a90da3560154f9c4f4a6e67c00415701d31e238|80000000|Taylor Swift|Celestial Sound Experience"
  "3|0xf350fb915de742726dea2b82784cad418465094842a60328ef83f9d7cdeaf603|120000000|Calvin Harris|Blockchain Beats Festival"
  "4|0x3e82f058241e23c8721b3ba86b9955abe91511bd6ba6fd87d7f17fb1a6f82f39|40000000|Ed Sheeran|Unplugged & Unchained"
  "5|0x2aae1bfa9195ffafec7725d65e9526789a6623c5892c415a5d62728c81124a31|70000000|Drake|Decentralized Sound Tour"
  "6|0xb5c7361ab5e9dd8f562da45941708186c71032609bcbab9cad27a623b0a435a1|60000000|Billie Eilish|Galaxy Tour 2026"
  "7|0xd9b7c4d17cbed32bdeae66517f1c74e5b280ef201c3efdb09720a20ce8b4f8a7|30000000|Bruno Mars|Smooth Grooves Night"
  "8|0x2821fafeb2a82c71f438fa198493ca22fc51911e133ac1c2aceb97c9f0425553|90000000|The Weeknd|Rock Revolution Tour"
  "9|0x560067d22b83da8ec09a846ee84b5dd3b9482bb5bbb1798d370d144782754635|100000000|Coldplay|Blockchain Classics"
  "10|0x21b9bf9b44625881b08079fe283ee8241c2ff238ae8928b6a16610e2131cb7b4|45000000|Post Malone|Country Roads Festival"
  "11|0x7a9b0fd2eb781618fc6ea1148ea3268ea8210370502b3d84e1c379a261abc5ef|70000000|Linkin Park|Metal Mayhem World Tour"
  "12|0xcc083ea621785389f6946458c22ee30234c059dc37769397ebdd3f2dff154868|35000000|Rihanna|Island Rhythms Festival"
  "13|0x0f8a5e41063bb429774befc0534ccd05394cb329176cf5514547665464cf6cd0|55000000|Shakira|Salsa Heat Night"
  "14|0x4b27339985045ea4f9a72349269abb87fe31a63af4a1f6b5e70e426357317aa8|65000000|Dua Lipa|Techno Underground"
  "15|0x2a4483c9e2e77bedd4bfaf29bfac5e2bb2dd528def318dedeebed27a70fb1f86|50000000|Adele|Blues Heritage Tour"
)

# ---- Begin SQL file ----
cat > "$SQL_FILE" << 'SQLHEADER'
-- ============================================================
-- Supabase: paste into SQL Editor and run.
-- Generated by scripts/4-init-waitlists.sh
-- Updates concert_object_id AND waitlist_object_id for all 15 concerts.
-- ============================================================

-- Add waitlist_object_id column if it doesn't already exist
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS waitlist_object_id TEXT;

SQLHEADER

FAILED=0

for entry in "${DATA[@]}"; do
  IFS='|' read -r SUPABASE_ID CONCERT_OBJECT_ID FACE_VALUE ARTIST EVENT_NAME <<< "$entry"

  echo -n "  [$SUPABASE_ID] $EVENT_NAME ... "

  RESULT=$(one client call \
    --package "$PACKAGE_ID" \
    --module ticket \
    --function create_waitlist \
    --args "$ADMIN_CAP_ID" "$CONCERT_OBJECT_ID" "$FACE_VALUE" \
    --gas-budget 10000000 \
    --json 2>/dev/null)

  WAITLIST_ID=$(echo "$RESULT" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for c in data.get('objectChanges', []):
    t = c.get('objectType', '')
    if '::ticket::Waitlist' in t and c.get('type') == 'created':
        print(c['objectId'])
        break
" 2>/dev/null)

  if [ -z "$WAITLIST_ID" ]; then
    echo "❌  FAILED"
    FAILED=$((FAILED + 1))
    echo "-- ❌ FAILED: $EVENT_NAME (id=$SUPABASE_ID)" >> "$SQL_FILE"
    continue
  fi

  echo "✅  $WAITLIST_ID"

  # Derive OCT price string
  PRICE_OCT=$(python3 -c "
mist = $FACE_VALUE
oct_val = mist / 1_000_000_000
s = f'{oct_val:.9f}'.rstrip('0')
if '.' in s:
    parts = s.split('.')
    dec = parts[1] if len(parts[1]) >= 2 else parts[1].ljust(2, '0')
    s = parts[0] + '.' + dec
print(s + ' OCT')
")

  cat >> "$SQL_FILE" << SQLROW
UPDATE concerts
SET concert_object_id   = '$CONCERT_OBJECT_ID',
    waitlist_object_id  = '$WAITLIST_ID',
    artist              = '$ARTIST',
    "availableTickets"  = 2,
    price               = '$PRICE_OCT'
WHERE id = '$SUPABASE_ID';   -- $EVENT_NAME

SQLROW

done

echo ""
if [ "$FAILED" -gt 0 ]; then
  echo "⚠️   $FAILED waitlist(s) failed — check output above."
else
  echo "🎉  All waitlists created successfully!"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NEXT STEP:"
echo "  1. Open Supabase → SQL Editor"
echo "  2. Paste the contents of:"
echo "     $SQL_FILE"
echo "  3. Run the query"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
