#!/bin/bash
# =============================================================
# TiX-One Step 4: Create Waitlist objects on-chain per concert
# Run ONCE after 2-seed-concerts.sh.
# Creates one shared Waitlist per concert and outputs full
# Supabase SQL to update both concert_object_id AND waitlist_object_id.
# =============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IDS_FILE="$SCRIPT_DIR/.deployed-ids.env"
SQL_FILE="$SCRIPT_DIR/supabase-update.sql"

# ---- Load deployed IDs ----
if [ ! -f "$IDS_FILE" ]; then
  echo "❌  $IDS_FILE not found."
  echo "    Run scripts/1-deploy.sh first."
  exit 1
fi
source "$IDS_FILE"

if [ -z "$PACKAGE_ID" ] || [ -z "$ADMIN_CAP_ID" ]; then
  echo "❌  PACKAGE_ID or ADMIN_CAP_ID is missing in $IDS_FILE"
  exit 1
fi

echo ""
echo "⏳  Creating Waitlist objects on-chain..."
echo "    Package   : $PACKAGE_ID"
echo "    Admin Cap : $ADMIN_CAP_ID"
echo ""

# ---- Concert data: "supabase_id|concert_object_id|face_value_mist|artist|event_name" ----
# These concert_object_ids were captured by 2-seed-concerts.sh
declare -a DATA=(
  "1|0x4c6c087a3b23343cf8e27a76c078ad21e33de51fd1eef0b6dbfc6794cbfeee3f|50000000|Martin Garrix|Neon Dreams Tour"
  "2|0x05fada3d2ab8c434d056a307b78eca92f79c3d4d3dcec29b047e626e98fb80fe|80000000|Taylor Swift|Celestial Sound Experience"
  "3|0x1fa756819407c0467fa6cd8208998ad233611d5f3b56f5718da9feb0c463453a|120000000|Calvin Harris|Blockchain Beats Festival"
  "4|0x422c0194ee907d0af7330bed774f6b24dc5d84a51ed16e09ba9dbc278b564193|40000000|Ed Sheeran|Unplugged & Unchained"
  "5|0x23423f1eafa0a5cb1be3e83a32dea4e224470999dd8911a9e01c65fc28403b1c|70000000|Drake|Decentralized Sound Tour"
  "6|0x273f3709d8348b15faf9019cac093261d7ff9e3e094b49494c839c3efe9eb1dc|60000000|Billie Eilish|Galaxy Tour 2026"
  "7|0x682f32a46312302dcea94009c94452788f3e037e179052a105a9b91f097e5084|30000000|Bruno Mars|Smooth Grooves Night"
  "8|0x480eabbd31286193b637b375f5b5d742702d36a9b1bf1b276182710d54071807|90000000|The Weeknd|Rock Revolution Tour"
  "9|0xeb91f46852f42806a5b938b1cf360c132c211b902617eb87af538c188b12e264|100000000|Coldplay|Blockchain Classics"
  "10|0x93519951a75a73a2587fb374a8640e24bea1d36b5385b038a30c3a25d80cbb75|45000000|Post Malone|Country Roads Festival"
  "11|0xe338dd7a026a525c945d1bf73246f4f93b368198f394d5beccb253b7729ee1d1|70000000|Linkin Park|Metal Mayhem World Tour"
  "12|0x942d95e6a3d9950a8cf32ae20a6d67366889c3c9abdcd767bd210fc5290207b2|35000000|Rihanna|Island Rhythms Festival"
  "13|0x7ed4bd1bfd47d4d9d3088224364c5c8d7e0005150ca2b0fcaeeb2be2e8182850|55000000|Shakira|Salsa Heat Night"
  "14|0xa1e972a4001205dae59eb983504c583012379284f5a4eeb88961f7f9cd5093e0|65000000|Dua Lipa|Techno Underground"
  "15|0xbce8cffd0f0bd3a7e5725143d34d8dd8ae94cda9cb10ab2ad320ab702d588df9|50000000|Adele|Blues Heritage Tour"
)

# ---- Begin SQL file ----
cat > "$SQL_FILE" << 'SQLHEADER'
-- ============================================================
-- Supabase: paste into SQL Editor and run.
-- Generated by scripts/4-init-waitlists.sh
-- Updates concert_object_id AND waitlist_object_id for all 15 concerts.
-- ============================================================

-- Add waitlist_object_id column if it doesn't already exist
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS waitlist_object_id TEXT;

SQLHEADER

FAILED=0

for entry in "${DATA[@]}"; do
  IFS='|' read -r SUPABASE_ID CONCERT_OBJECT_ID FACE_VALUE ARTIST EVENT_NAME <<< "$entry"

  echo -n "  [$SUPABASE_ID] $EVENT_NAME ... "

  RESULT=$(one client call \
    --package "$PACKAGE_ID" \
    --module ticket \
    --function create_waitlist \
    --args "$ADMIN_CAP_ID" "$CONCERT_OBJECT_ID" "$FACE_VALUE" \
    --gas-budget 10000000 \
    --json 2>/dev/null)

  WAITLIST_ID=$(echo "$RESULT" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for c in data.get('objectChanges', []):
    t = c.get('objectType', '')
    if '::ticket::Waitlist' in t and c.get('type') == 'created':
        print(c['objectId'])
        break
" 2>/dev/null)

  if [ -z "$WAITLIST_ID" ]; then
    echo "❌  FAILED"
    FAILED=$((FAILED + 1))
    echo "-- ❌ FAILED: $EVENT_NAME (id=$SUPABASE_ID)" >> "$SQL_FILE"
    continue
  fi

  echo "✅  $WAITLIST_ID"

  # Derive OCT price string
  PRICE_OCT=$(python3 -c "
mist = $FACE_VALUE
oct_val = mist / 1_000_000_000
s = f'{oct_val:.9f}'.rstrip('0')
if '.' in s:
    parts = s.split('.')
    dec = parts[1] if len(parts[1]) >= 2 else parts[1].ljust(2, '0')
    s = parts[0] + '.' + dec
print(s + ' OCT')
")

  cat >> "$SQL_FILE" << SQLROW
UPDATE concerts
SET concert_object_id   = '$CONCERT_OBJECT_ID',
    waitlist_object_id  = '$WAITLIST_ID',
    artist              = '$ARTIST',
    "availableTickets"  = 2,
    price               = '$PRICE_OCT'
WHERE id = '$SUPABASE_ID';   -- $EVENT_NAME

SQLROW

done

echo ""
if [ "$FAILED" -gt 0 ]; then
  echo "⚠️   $FAILED waitlist(s) failed — check output above."
else
  echo "🎉  All waitlists created successfully!"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NEXT STEP:"
echo "  1. Open Supabase → SQL Editor"
echo "  2. Paste the contents of:"
echo "     $SQL_FILE"
echo "  3. Run the query"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
