-- ============================================================
-- Supabase: paste into SQL Editor and run.
-- Generated by scripts/4-init-waitlists.sh
-- Updates concert_object_id AND waitlist_object_id for all 15 concerts.
-- ============================================================

-- Add waitlist_object_id column if it doesn't already exist
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS waitlist_object_id TEXT;

UPDATE concerts
SET concert_object_id   = '0xa44532d726037600dd0794a51a840f6a425da3461f20ded52cc26f687a8c1fb3',
    waitlist_object_id  = '0x1ab48e031118dd2c328ef830d4c95c0871697b8047f32045766fc530908485af',
    artist              = 'Martin Garrix',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '1';   -- Neon Dreams Tour

UPDATE concerts
SET concert_object_id   = '0x3bb456f38018f41e215148220a90da3560154f9c4f4a6e67c00415701d31e238',
    waitlist_object_id  = '0x5ce6e4f35c130702569d70d4aadc7ecead5671b8250f84769df032bf2dea6500',
    artist              = 'Taylor Swift',
    "availableTickets"  = 2,
    price               = '0.08 OCT'
WHERE id = '2';   -- Celestial Sound Experience

UPDATE concerts
SET concert_object_id   = '0xf350fb915de742726dea2b82784cad418465094842a60328ef83f9d7cdeaf603',
    waitlist_object_id  = '0x8190a1b899990cb3f12363d6e3ed924f21c9172149acadcf4f914d772c160895',
    artist              = 'Calvin Harris',
    "availableTickets"  = 2,
    price               = '0.12 OCT'
WHERE id = '3';   -- Blockchain Beats Festival

UPDATE concerts
SET concert_object_id   = '0x3e82f058241e23c8721b3ba86b9955abe91511bd6ba6fd87d7f17fb1a6f82f39',
    waitlist_object_id  = '0x0b3254f00dc10653f0e0ae1d5be0b1e69de574377bc352cd1842f01fd73c976c',
    artist              = 'Ed Sheeran',
    "availableTickets"  = 2,
    price               = '0.04 OCT'
WHERE id = '4';   -- Unplugged & Unchained

UPDATE concerts
SET concert_object_id   = '0x2aae1bfa9195ffafec7725d65e9526789a6623c5892c415a5d62728c81124a31',
    waitlist_object_id  = '0x1c89c1f4de762f4430ca89903c3ab371794116a82407314d547ba0d632166a35',
    artist              = 'Drake',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '5';   -- Decentralized Sound Tour

UPDATE concerts
SET concert_object_id   = '0xb5c7361ab5e9dd8f562da45941708186c71032609bcbab9cad27a623b0a435a1',
    waitlist_object_id  = '0x2ad453a5c12ad2b804a419b6d440abbb5f61b6e4a037469c96b588faecd34657',
    artist              = 'Billie Eilish',
    "availableTickets"  = 2,
    price               = '0.06 OCT'
WHERE id = '6';   -- Galaxy Tour 2026

UPDATE concerts
SET concert_object_id   = '0xd9b7c4d17cbed32bdeae66517f1c74e5b280ef201c3efdb09720a20ce8b4f8a7',
    waitlist_object_id  = '0x1981929c38d9d9cf75b3da4db69ea7e29e667a32832c0feebad77bd00edcf4b5',
    artist              = 'Bruno Mars',
    "availableTickets"  = 2,
    price               = '0.03 OCT'
WHERE id = '7';   -- Smooth Grooves Night

UPDATE concerts
SET concert_object_id   = '0x2821fafeb2a82c71f438fa198493ca22fc51911e133ac1c2aceb97c9f0425553',
    waitlist_object_id  = '0x3166fc4fd1610db21ff470f27f20db14942160b2ae52366604eb2ba8f641fcef',
    artist              = 'The Weeknd',
    "availableTickets"  = 2,
    price               = '0.09 OCT'
WHERE id = '8';   -- Rock Revolution Tour

UPDATE concerts
SET concert_object_id   = '0x560067d22b83da8ec09a846ee84b5dd3b9482bb5bbb1798d370d144782754635',
    waitlist_object_id  = '0xcfabc65d5f9a093227beb1477c0a69da4841697981c5fa5bc9306bb96862b0fe',
    artist              = 'Coldplay',
    "availableTickets"  = 2,
    price               = '0.10 OCT'
WHERE id = '9';   -- Blockchain Classics

UPDATE concerts
SET concert_object_id   = '0x21b9bf9b44625881b08079fe283ee8241c2ff238ae8928b6a16610e2131cb7b4',
    waitlist_object_id  = '0xa448b93893576ca1a5ffb5d57a72420601c5ddb653838d86618d55b367e1f79f',
    artist              = 'Post Malone',
    "availableTickets"  = 2,
    price               = '0.045 OCT'
WHERE id = '10';   -- Country Roads Festival

UPDATE concerts
SET concert_object_id   = '0x7a9b0fd2eb781618fc6ea1148ea3268ea8210370502b3d84e1c379a261abc5ef',
    waitlist_object_id  = '0x2982e67f5738a3557669087efdda461068236ff8dcfb9a90aceffe2d62123a20',
    artist              = 'Linkin Park',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '11';   -- Metal Mayhem World Tour

UPDATE concerts
SET concert_object_id   = '0xcc083ea621785389f6946458c22ee30234c059dc37769397ebdd3f2dff154868',
    waitlist_object_id  = '0x51c5dfeb87777749794322c732d1fe83be4e42d368008b1f67cbdf8b3dccd17f',
    artist              = 'Rihanna',
    "availableTickets"  = 2,
    price               = '0.035 OCT'
WHERE id = '12';   -- Island Rhythms Festival

UPDATE concerts
SET concert_object_id   = '0x0f8a5e41063bb429774befc0534ccd05394cb329176cf5514547665464cf6cd0',
    waitlist_object_id  = '0xc275ba563e8211563e4bbab02fb7ab3ea8d6b5274172706d92468a95239372e7',
    artist              = 'Shakira',
    "availableTickets"  = 2,
    price               = '0.055 OCT'
WHERE id = '13';   -- Salsa Heat Night

UPDATE concerts
SET concert_object_id   = '0x4b27339985045ea4f9a72349269abb87fe31a63af4a1f6b5e70e426357317aa8',
    waitlist_object_id  = '0xc174d4ec2b1b9d2a36f84bbccff4e030064506f98eb8dbbedabe9d530244eb54',
    artist              = 'Dua Lipa',
    "availableTickets"  = 2,
    price               = '0.065 OCT'
WHERE id = '14';   -- Techno Underground

UPDATE concerts
SET concert_object_id   = '0x2a4483c9e2e77bedd4bfaf29bfac5e2bb2dd528def318dedeebed27a70fb1f86',
    waitlist_object_id  = '0xe9fcbcbf0c720ed95fba3054833db67c9d5bb7fdfa5e4b11338c35c9558999d5',
    artist              = 'Adele',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '15';   -- Blues Heritage Tour

