-- ============================================================
-- Supabase: paste into SQL Editor and run.
-- Generated by scripts/4-init-waitlists.sh
-- Updates concert_object_id AND waitlist_object_id for all 15 concerts.
-- ============================================================

-- Add waitlist_object_id column if it doesn't already exist
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS waitlist_object_id TEXT;

UPDATE concerts
SET concert_object_id   = '0x4c6c087a3b23343cf8e27a76c078ad21e33de51fd1eef0b6dbfc6794cbfeee3f',
    waitlist_object_id  = '0x394dc22f622dc04b4866de90d934c7780c8aea862983e3e95ed4ad8ce18b17a0',
    artist              = 'Martin Garrix',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '1';   -- Neon Dreams Tour

UPDATE concerts
SET concert_object_id   = '0x05fada3d2ab8c434d056a307b78eca92f79c3d4d3dcec29b047e626e98fb80fe',
    waitlist_object_id  = '0x6c78871c90f72ab631febeb6fb230a8e3d4f5c1f90f7e3657f4e46f1d9c999b3',
    artist              = 'Taylor Swift',
    "availableTickets"  = 2,
    price               = '0.08 OCT'
WHERE id = '2';   -- Celestial Sound Experience

UPDATE concerts
SET concert_object_id   = '0x1fa756819407c0467fa6cd8208998ad233611d5f3b56f5718da9feb0c463453a',
    waitlist_object_id  = '0x2e6d107f30870e7b2cf09b4ba9996bb79892f060eab4cec89cce80eda0b2f060',
    artist              = 'Calvin Harris',
    "availableTickets"  = 2,
    price               = '0.12 OCT'
WHERE id = '3';   -- Blockchain Beats Festival

UPDATE concerts
SET concert_object_id   = '0x422c0194ee907d0af7330bed774f6b24dc5d84a51ed16e09ba9dbc278b564193',
    waitlist_object_id  = '0x22891b1bc7ef4102e66e4fe3e9d7ffdfd4e0da0df587a952ac69c759e954fd30',
    artist              = 'Ed Sheeran',
    "availableTickets"  = 2,
    price               = '0.04 OCT'
WHERE id = '4';   -- Unplugged & Unchained

UPDATE concerts
SET concert_object_id   = '0x23423f1eafa0a5cb1be3e83a32dea4e224470999dd8911a9e01c65fc28403b1c',
    waitlist_object_id  = '0xaccf3a85a0128a6d04ace3e465d022eb14069b3b0efe32495e89341a71db956e',
    artist              = 'Drake',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '5';   -- Decentralized Sound Tour

UPDATE concerts
SET concert_object_id   = '0x273f3709d8348b15faf9019cac093261d7ff9e3e094b49494c839c3efe9eb1dc',
    waitlist_object_id  = '0x4a53d30db528542f6a62d1c2e6780fb3d509445b139cddc6ecde05197a7d8c7a',
    artist              = 'Billie Eilish',
    "availableTickets"  = 2,
    price               = '0.06 OCT'
WHERE id = '6';   -- Galaxy Tour 2026

UPDATE concerts
SET concert_object_id   = '0x682f32a46312302dcea94009c94452788f3e037e179052a105a9b91f097e5084',
    waitlist_object_id  = '0xb4c8016dc40b5fc3a3ddbd02a2cdc1a2dd9ab73a2897c0fc05c3f0a3d5f53b41',
    artist              = 'Bruno Mars',
    "availableTickets"  = 2,
    price               = '0.03 OCT'
WHERE id = '7';   -- Smooth Grooves Night

UPDATE concerts
SET concert_object_id   = '0x480eabbd31286193b637b375f5b5d742702d36a9b1bf1b276182710d54071807',
    waitlist_object_id  = '0x27ffa4c01acbcb8cac13b05d4e55fe83201632c8652ca350edc55b00642654df',
    artist              = 'The Weeknd',
    "availableTickets"  = 2,
    price               = '0.09 OCT'
WHERE id = '8';   -- Rock Revolution Tour

UPDATE concerts
SET concert_object_id   = '0xeb91f46852f42806a5b938b1cf360c132c211b902617eb87af538c188b12e264',
    waitlist_object_id  = '0x60a5df2cd261122eda6dd076f662f92ca45b8c26d098bb2209fd58624483c621',
    artist              = 'Coldplay',
    "availableTickets"  = 2,
    price               = '0.10 OCT'
WHERE id = '9';   -- Blockchain Classics

UPDATE concerts
SET concert_object_id   = '0x93519951a75a73a2587fb374a8640e24bea1d36b5385b038a30c3a25d80cbb75',
    waitlist_object_id  = '0xaaf182f4f8a982379d974c8b507099a1546f60da6f54799c3a6591f20ba744c3',
    artist              = 'Post Malone',
    "availableTickets"  = 2,
    price               = '0.045 OCT'
WHERE id = '10';   -- Country Roads Festival

UPDATE concerts
SET concert_object_id   = '0xe338dd7a026a525c945d1bf73246f4f93b368198f394d5beccb253b7729ee1d1',
    waitlist_object_id  = '0x42f03d71fdd527385b0c029462ef21d45f6fb69bbeb6fb976ec27dd1c22ec122',
    artist              = 'Linkin Park',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '11';   -- Metal Mayhem World Tour

UPDATE concerts
SET concert_object_id   = '0x942d95e6a3d9950a8cf32ae20a6d67366889c3c9abdcd767bd210fc5290207b2',
    waitlist_object_id  = '0xd1de95918d8c3e356aeb2bce1d3964a1fbfa15510e1f5663c8d55a0fd1ea104d',
    artist              = 'Rihanna',
    "availableTickets"  = 2,
    price               = '0.035 OCT'
WHERE id = '12';   -- Island Rhythms Festival

UPDATE concerts
SET concert_object_id   = '0x7ed4bd1bfd47d4d9d3088224364c5c8d7e0005150ca2b0fcaeeb2be2e8182850',
    waitlist_object_id  = '0x025eb43f2c99d2871a3fa69ba94608d4ec3911748cd89cce950837646187c366',
    artist              = 'Shakira',
    "availableTickets"  = 2,
    price               = '0.055 OCT'
WHERE id = '13';   -- Salsa Heat Night

UPDATE concerts
SET concert_object_id   = '0xa1e972a4001205dae59eb983504c583012379284f5a4eeb88961f7f9cd5093e0',
    waitlist_object_id  = '0x434e635a6766c95001e7397b18e4e05d59117a9291235ca6c8326bbd515c338c',
    artist              = 'Dua Lipa',
    "availableTickets"  = 2,
    price               = '0.065 OCT'
WHERE id = '14';   -- Techno Underground

UPDATE concerts
SET concert_object_id   = '0xbce8cffd0f0bd3a7e5725143d34d8dd8ae94cda9cb10ab2ad320ab702d588df9',
    waitlist_object_id  = '0xd64df3a7f50da0fc8d41e29983f56f058f15a43c97fcb50f59b664c576a3966b',
    artist              = 'Adele',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '15';   -- Blues Heritage Tour

