-- ============================================================
-- Supabase: paste this into the SQL Editor to link on-chain IDs
-- Generated by scripts/2-seed-concerts.sh
-- ============================================================

UPDATE concerts
SET concert_object_id   = '0xb2c18c89d800ef5a8cca715daa3624df4a36ecaa553df3d0b6b7d855c3b53190',
    artist              = 'Martin Garrix',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '1';   -- Neon Dreams Tour

UPDATE concerts
SET concert_object_id   = '0x80bbc67b80eef76889656298a03781fe85be1e51862cefbbccdbf5ddd0940a0e',
    artist              = 'Taylor Swift',
    "availableTickets"  = 2,
    price               = '0.08 OCT'
WHERE id = '2';   -- Celestial Sound Experience

UPDATE concerts
SET concert_object_id   = '0x3a7324e1517adec5d9900c99129af2e37da528b34f6cd63e7250bddcca9840cd',
    artist              = 'Calvin Harris',
    "availableTickets"  = 2,
    price               = '0.12 OCT'
WHERE id = '3';   -- Blockchain Beats Festival

UPDATE concerts
SET concert_object_id   = '0x567bf5f209eed960ff8577a6621bf44be6e21355ddd8782478c2e21dbd08e112',
    artist              = 'Ed Sheeran',
    "availableTickets"  = 2,
    price               = '0.04 OCT'
WHERE id = '4';   -- Unplugged & Unchained

UPDATE concerts
SET concert_object_id   = '0x28b5f4294d5dffc9c43ddea4de3962e7078ca832a76c3fb7f944f6156b4f3045',
    artist              = 'Drake',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '5';   -- Decentralized Sound Tour

UPDATE concerts
SET concert_object_id   = '0x16a50eb554888239caeed8908e4cb171ca311e219f3cef1c1452e75919e902aa',
    artist              = 'Billie Eilish',
    "availableTickets"  = 2,
    price               = '0.06 OCT'
WHERE id = '6';   -- Galaxy Tour 2026

UPDATE concerts
SET concert_object_id   = '0xb8cd2d8e0ddf6fc81af72bc8eaf211ec795dd1bdfff0c8b68929cbb4706bda4f',
    artist              = 'Bruno Mars',
    "availableTickets"  = 2,
    price               = '0.03 OCT'
WHERE id = '7';   -- Smooth Grooves Night

UPDATE concerts
SET concert_object_id   = '0xfaeadead97d02f6b4b2d29eb80e2cbd0a791e7d66b22f260da0523cf47f18a8d',
    artist              = 'The Weeknd',
    "availableTickets"  = 2,
    price               = '0.09 OCT'
WHERE id = '8';   -- Rock Revolution Tour

UPDATE concerts
SET concert_object_id   = '0x18d0b799360851e54cd36b5f23736c1e556524b60ebe4f41e6e94dd5be826c1d',
    artist              = 'Coldplay',
    "availableTickets"  = 2,
    price               = '0.10 OCT'
WHERE id = '9';   -- Blockchain Classics

UPDATE concerts
SET concert_object_id   = '0x347e92fffd88f29d61be81a5a6368676133270bae154c67490bdda4a12d3b684',
    artist              = 'Post Malone',
    "availableTickets"  = 2,
    price               = '0.045 OCT'
WHERE id = '10';   -- Country Roads Festival

UPDATE concerts
SET concert_object_id   = '0x545ed549556ddc8ca246233e4ec60e95b37406ace0036de766c18b87c4030fcd',
    artist              = 'Linkin Park',
    "availableTickets"  = 2,
    price               = '0.07 OCT'
WHERE id = '11';   -- Metal Mayhem World Tour

UPDATE concerts
SET concert_object_id   = '0x7ed6968453495374fdb63cafc44834f06a5cc3e9acff4be88b0d360a59154a89',
    artist              = 'Rihanna',
    "availableTickets"  = 2,
    price               = '0.035 OCT'
WHERE id = '12';   -- Island Rhythms Festival

UPDATE concerts
SET concert_object_id   = '0x7df23eca6d02237b2b702cda14f88fd3b77e3a6d572b8d0898a52e695c41f49d',
    artist              = 'Shakira',
    "availableTickets"  = 2,
    price               = '0.055 OCT'
WHERE id = '13';   -- Salsa Heat Night

UPDATE concerts
SET concert_object_id   = '0x234f79c9082f831b2f7092960c4ccba1e8b742eaf358af0681419f4646fe341d',
    artist              = 'Dua Lipa',
    "availableTickets"  = 2,
    price               = '0.065 OCT'
WHERE id = '14';   -- Techno Underground

UPDATE concerts
SET concert_object_id   = '0x99aee719010017fbe01f5ecf2ffcf64cb3a3a78df2ae9a0a86da7416b0bdb8f9',
    artist              = 'Adele',
    "availableTickets"  = 2,
    price               = '0.05 OCT'
WHERE id = '15';   -- Blues Heritage Tour
